botName: "봇토리"
defaultResponse: "무슨 말씀이신지 잘 모르겠어요."

dialogs:
  - keyword: "안녕"
    response: "안녕하세요! 만나서 반가워요."
  
  - keyword: "이름이 뭐야"
    response: "제 이름은 봇토리입니다."

  - keyword: "잘가"
    response: "안녕히 가세요!"